### ISSUE TITLE
Not an issue but a QoL wish

### ISSUE THREAD

**Issue by At-Libitum** [ifabijanovic/swtor-holonet#1]
Hi, great app so far, have a wish though. Now I know this is not really in the scope of this app, but sometimes I would love it if it were one of the 'Open With' applications when I long-tap a swtor forum link or dulfy link in for instance Twitter. 
I realize that it would then also show in any other app as 'Open With' candidate when long-tapping on a link, but maybe filtering that the target link must be either on the forum or dulfy to actually open the app, otherwise spit out a error popup if it still gets chosen (if that is within the available options that is, otherwise it's an almost impossible wish I guess)

Raj

**Comment by ifabijanovic** [comment]
That sounds like a really interesting proposal, I will look into it.

**Comment by ifabijanovic** [comment]
I will be looking into this for the next release

**Comment by ifabijanovic** [comment]
It seems it is not possible to do this in a clean manner. If I was the owner of the www.swtor.com site (which I'm obviously not 🙂) this could be achieved with [Universal links](https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html). 

Only other solution I can think of is doing a javascript hack in an Action extension to transfer to the app, but that would:

* provide a bad user experience
* probably be rejected by Apple
* be a hack and I don't like solutions like that 🙂
